# Secure Properties - Development Environment

# TLS/SSL Passwords
tls.keystore.password=![changeit]
tls.keystore.key.password=![changeit]
tls.truststore.password=![changeit]

# MDM Database Credentials
mdm.db.user=![mdm_dev_user]
mdm.db.password=![mdm_dev_password]

# MDM HTTP API Credentials
mdm.api.username=![mdm_api_dev_user]
mdm.api.password=![mdm_api_dev_password]

# Secure Key
secure.key=![dev-encryption-key]
